name: Create release zip file from tagged versions

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: SpellCoda must be name of top level dir containing addon
        run: |
          mkdir -p SpellCoda
          mv * SpellCoda

      - name: Get tag name
        id: get_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release archive
        run: |
          zip -r ${{ steps.get_tag.outputs.TAG_NAME }}.zip SpellCoda/

      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.get_tag.outputs.TAG_NAME }}.zip
          asset_name: ${{ steps.get_tag.outputs.TAG_NAME }}.zip
          asset_content_type: application/zip
